export const stocksArr = [
  {
    symbol: "AAPL",
    revenue: "387.54B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/aapl.png",
    companyName: "Apple Inc.",
    marketCap: "2,251.36B",
    priceChange: "-3.67%",
    price: 140.09,
  },
  {
    symbol: "MSFT",
    revenue: "198.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MSFT.png",
    companyName: "Microsoft Corporation",
    marketCap: "1,746.94B",
    priceChange: "-5.09%",
    price: 234.24,
  },
  {
    symbol: "GOOGL",
    revenue: "278.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/googl.png",
    companyName: "Alphabet, Inc.",
    marketCap: "1,292.67B",
    priceChange: "-2.70%",
    price: 98.68,
  },
  {
    symbol: "AMZN",
    revenue: "485.90B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/amzn.png",
    companyName: "Amazon.com, Inc.",
    marketCap: "1,167.09B",
    priceChange: "-4.77%",
    price: 114.56,
  },
  {
    symbol: "TSLA",
    revenue: "67.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TSLA.png",
    companyName: "Tesla, Inc.",
    marketCap: "698.98B",
    priceChange: "-6.32%",
    price: 223.07,
  },
  {
    symbol: "UNH",
    revenue: "306.56B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/unh.png",
    companyName: "UnitedHealth Group Incorporated",
    marketCap: "472.23B",
    priceChange: "-2.75%",
    price: 504.85,
  },
  {
    symbol: "JNJ",
    revenue: "95.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/JNJ.png",
    companyName: "Johnson & Johnson",
    marketCap: "421.19B",
    priceChange: "-1.06%",
    price: 160.2,
  },
  {
    symbol: "XOM",
    revenue: "364.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/XOM.png",
    companyName: "Exxon Mobil Corporation",
    marketCap: "421.06B",
    priceChange: "-1.01%",
    price: 101.03,
  },
  {
    symbol: "V",
    revenue: "28.08B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/v.png",
    companyName: "Visa Inc.",
    marketCap: "387.41B",
    priceChange: "-0.95%",
    price: 183.83,
  },
  {
    symbol: "TSM",
    revenue: "63.02B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/tsm.png",
    companyName: "Taiwan Semiconductor Manufacturing Company Limited",
    marketCap: "359.81B",
    priceChange: "-6.19%",
    price: 69.75,
  },
  {
    symbol: "META",
    revenue: "119.41B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/meta.png",
    companyName: "Meta Platforms, Inc.",
    marketCap: "358.65B",
    priceChange: "-4.04%",
    price: 133.45,
  },
  {
    symbol: "WMT",
    revenue: "587.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/wmt.png",
    companyName: "Walmart, Inc.",
    marketCap: "348.94B",
    priceChange: "-2.37%",
    price: 128.56,
  },
  {
    symbol: "CVX",
    revenue: "215.97B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cvx.png",
    companyName: "Chevron Corporation",
    marketCap: "313.25B",
    priceChange: "-0.86%",
    price: 160.03,
  },
  {
    symbol: "JPM",
    revenue: "120.34B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/JPM.png",
    companyName: "JPMorgan Chase & Co.",
    marketCap: "310.79B",
    priceChange: "-2.00%",
    price: 105.98,
  },
  {
    symbol: "LLY",
    revenue: "29.07B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LLY.png",
    companyName: "Eli Lilly and Company",
    marketCap: "310.38B",
    priceChange: "-1.89%",
    price: 326.66,
  },
  {
    symbol: "NVDA",
    revenue: "29.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NVDA.png",
    companyName: "NVIDIA Corporation",
    marketCap: "300.93B",
    priceChange: "-8.03%",
    price: 120.76,
  },
  {
    symbol: "PG",
    revenue: "80.19B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PG.png",
    companyName: "The Procter & Gamble Company",
    marketCap: "296.45B",
    priceChange: "-1.75%",
    price: 124.27,
  },
  {
    symbol: "HD",
    revenue: "155.24B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/hd.png",
    companyName: "The Home Depot, Inc.",
    marketCap: "291.07B",
    priceChange: "-2.09%",
    price: 284.32,
  },
  {
    symbol: "MA",
    revenue: "20.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ma.png",
    companyName: "Mastercard Incorporated",
    marketCap: "285.05B",
    priceChange: "-1.42%",
    price: 294.97,
  },
  {
    symbol: "BAC",
    revenue: "90.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bac.png",
    companyName: "Bank of America Corporation",
    marketCap: "247.08B",
    priceChange: "-2.26%",
    price: 30.75,
  },
  {
    symbol: "ABBV",
    revenue: "57.35B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/abbv.png",
    companyName: "AbbVie Inc.",
    marketCap: "245.34B",
    priceChange: "-1.09%",
    price: 138.76,
  },
  {
    symbol: "NVO",
    revenue: "22.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NVO.png",
    companyName: "Novo Nordisk A/S",
    marketCap: "240.62B",
    priceChange: "-1.66%",
    price: 104.06,
  },
  {
    symbol: "PFE",
    revenue: "101.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pfe.png",
    companyName: "Pfizer Inc.",
    marketCap: "237.51B",
    priceChange: "-1.79%",
    price: 42.32,
  },
  {
    symbol: "KO",
    revenue: "41.32B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ko.png",
    companyName: "The Coca-Cola Company",
    marketCap: "235.74B",
    priceChange: "-0.95%",
    price: 54.51,
  },
  {
    symbol: "PEP",
    revenue: "81.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pep.png",
    companyName: "PepsiCo, Inc.",
    marketCap: "223.03B",
    priceChange: "-0.73%",
    price: 161.61,
  },
  {
    symbol: "MRK",
    revenue: "57.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mrk.png",
    companyName: "Merck & Co., Inc.",
    marketCap: "221.92B",
    priceChange: "0.18%",
    price: 87.6,
  },
  {
    symbol: "BABA",
    revenue: "127.30B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/baba.png",
    companyName: "Alibaba Group Holding Ltd",
    marketCap: "219.48B",
    priceChange: "-3.65%",
    price: 81.24,
  },
  {
    symbol: "COST",
    revenue: "226.95B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cost.png",
    companyName: "Costco Wholesale Corporation",
    marketCap: "207.21B",
    priceChange: "-2.97%",
    price: 468.15,
  },
  {
    symbol: "TMO",
    revenue: "42.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/tmo.png",
    companyName: "Thermo Fisher Scientific, Inc.",
    marketCap: "205.14B",
    priceChange: "-3.14%",
    price: 523.61,
  },
  {
    symbol: "DHR",
    revenue: "30.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dhr.png",
    companyName: "Danaher Corporation",
    marketCap: "195.30B",
    priceChange: "-3.44%",
    price: 268.48,
  },
  {
    symbol: "ASML",
    revenue: "20.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ASML.png",
    companyName: "ASML Holding N.V.",
    marketCap: "187.56B",
    priceChange: "-6.03%",
    price: 434.26,
  },
  {
    symbol: "AVGO",
    revenue: "31.68B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/avgo.png",
    companyName: "Broadcom Inc.",
    marketCap: "186.50B",
    priceChange: "-3.97%",
    price: 460.48,
  },
  {
    symbol: "TM",
    revenue: "234.47B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TM.png",
    companyName: "Toyota Motor Corporation",
    marketCap: "185.33B",
    priceChange: "-0.24%",
    price: 135.85,
  },
  {
    symbol: "BHP",
    revenue: "65.10B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BHP.png",
    companyName: "BHP Group Limited",
    marketCap: "184.23B",
    priceChange: "-0.76%",
    price: 51.18,
  },
  {
    symbol: "DIS",
    revenue: "81.11B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dis.png",
    companyName: "The Walt Disney Company",
    marketCap: "177.13B",
    priceChange: "-2.88%",
    price: 97.16,
  },
  {
    symbol: "TMUS",
    revenue: "80.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TMUS.png",
    companyName: "T-Mobile US, Inc.",
    marketCap: "172.54B",
    priceChange: "-1.31%",
    price: 137.59,
  },
  {
    symbol: "MCD",
    revenue: "23.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MCD.png",
    companyName: "McDonald's Corporation",
    marketCap: "171.56B",
    priceChange: "-0.67%",
    price: 233.19,
  },
  {
    symbol: "ORCL",
    revenue: "44.16B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/orcl.png",
    companyName: "Oracle Corporation",
    marketCap: "170.64B",
    priceChange: "-3.08%",
    price: 63.29,
  },
  {
    symbol: "NVS",
    revenue: "52.79B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NVS.png",
    companyName: "Novartis AG",
    marketCap: "166.52B",
    priceChange: "-0.51%",
    price: 75.65,
  },
  {
    symbol: "CSCO",
    revenue: "51.56B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CSCO.png",
    companyName: "Cisco Systems, Inc.",
    marketCap: "165.46B",
    priceChange: "-3.01%",
    price: 40.27,
  },
  {
    symbol: "ACN",
    revenue: "59.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/acn.png",
    companyName: "Accenture plc",
    marketCap: "164.27B",
    priceChange: "-3.62%",
    price: 259.71,
  },
  {
    symbol: "WFC",
    revenue: "74.31B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WFC.png",
    companyName: "Wells Fargo & Company",
    marketCap: "158.51B",
    priceChange: "-1.07%",
    price: 41.79,
  },
  {
    symbol: "VZ",
    revenue: "134.33B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/vz.png",
    companyName: "Verizon Communications, Inc.",
    marketCap: "154.76B",
    priceChange: "-2.62%",
    price: 36.85,
  },
  {
    symbol: "COP",
    revenue: "68.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/COP.png",
    companyName: "ConocoPhillips",
    marketCap: "150.87B",
    priceChange: "0.73%",
    price: 118.51,
  },
  {
    symbol: "NEE",
    revenue: "17.49B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/nee.png",
    companyName: "NextEra Energy, Inc.",
    marketCap: "150.76B",
    priceChange: "-2.76%",
    price: 76.73,
  },
  {
    symbol: "CRM",
    revenue: "29.32B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CRM.png",
    companyName: "Salesforce.com Inc",
    marketCap: "150.29B",
    priceChange: "-3.33%",
    price: 150.29,
  },
  {
    symbol: "BMY",
    revenue: "47.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bmy.png",
    companyName: "Bristol-Myers Squibb Company",
    marketCap: "148.83B",
    priceChange: "-0.77%",
    price: 69.7,
  },
  {
    symbol: "FMX",
    revenue: "27.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/FMX.png",
    companyName: "Fomento Economico Mexicano SAB de CV",
    marketCap: "146.10B",
    priceChange: "-2.06%",
    price: 63.67,
  },
  {
    symbol: "TXN",
    revenue: "19.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TXN.png",
    companyName: "Texas Instruments Incorporated",
    marketCap: "144.70B",
    priceChange: "-4.36%",
    price: 159.28,
  },
  {
    symbol: "SCHW",
    revenue: "19.04B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/schw.png",
    companyName: "The Charles Schwab Corporation",
    marketCap: "140.97B",
    priceChange: "-2.21%",
    price: 74.31,
  },
  {
    symbol: "ADBE",
    revenue: "17.19B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ADBE.png",
    companyName: "Adobe Inc.",
    marketCap: "138.73B",
    priceChange: "-3.23%",
    price: 288.77,
  },
  {
    symbol: "UPS",
    revenue: "100.10B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/UPS.png",
    companyName: "United Parcel Service, Inc.",
    marketCap: "137.66B",
    priceChange: "-3.90%",
    price: 159.14,
  },
  {
    symbol: "NKE",
    revenue: "47.15B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/nke.png",
    companyName: "Nike, Inc.",
    marketCap: "136.37B",
    priceChange: "-3.34%",
    price: 87.16,
  },
  {
    symbol: "LIN",
    revenue: "32.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LIN.png",
    companyName: "Linde plc",
    marketCap: "136.15B",
    priceChange: "-2.02%",
    price: 273.2,
  },
  {
    symbol: "QCOM",
    revenue: "42.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/QCOM.png",
    companyName: "Qualcomm Incorporated",
    marketCap: "135.78B",
    priceChange: "-3.49%",
    price: 120.91,
  },
  {
    symbol: "MS",
    revenue: "57.21B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ms.png",
    companyName: "Morgan Stanley",
    marketCap: "135.51B",
    priceChange: "-2.93%",
    price: 78.93,
  },
  {
    symbol: "PM",
    revenue: "82.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PM.png",
    companyName: "Philip Morris International Inc.",
    marketCap: "131.22B",
    priceChange: "-0.96%",
    price: 84.65,
  },
  {
    symbol: "CMCSA",
    revenue: "121.66B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CMCSA.png",
    companyName: "Comcast Corporation",
    marketCap: "129.18B",
    priceChange: "-2.60%",
    price: 29.27,
  },
  {
    symbol: "RTX",
    revenue: "65.29B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RTX.png",
    companyName: "Raytheon Technologies Corporation",
    marketCap: "123.64B",
    priceChange: "-0.32%",
    price: 84.01,
  },
  {
    symbol: "LOW",
    revenue: "95.39B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LOW.png",
    companyName: "Lowe's Companies, Inc.",
    marketCap: "122.41B",
    priceChange: "-1.39%",
    price: 197.21,
  },
  {
    symbol: "UNP",
    revenue: "23.43B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/UNP.png",
    companyName: "Union Pacific Corporation",
    marketCap: "122.16B",
    priceChange: "-1.31%",
    price: 195.62,
  },
  {
    symbol: "UL",
    revenue: "59.24B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/UL.png",
    companyName: "Unilever PLC",
    marketCap: "113.45B",
    priceChange: "-0.87%",
    price: 43.35,
  },
  {
    symbol: "EQNR",
    revenue: "90.92B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/EQNR.png",
    companyName: "Equinor ASA",
    marketCap: "111.45B",
    priceChange: "-0.20%",
    price: 35.24,
  },
  {
    symbol: "INTU",
    revenue: "12.73B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/INTU.png",
    companyName: "Intuit Inc.",
    marketCap: "110.76B",
    priceChange: "-4.46%",
    price: 392.96,
  },
  {
    symbol: "MDT",
    revenue: "31.07B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MDT.png",
    companyName: "Medtronic plc.",
    marketCap: "109.55B",
    priceChange: "-2.37%",
    price: 82.42,
  },
  {
    symbol: "TD",
    revenue: "34.16B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TD.png",
    companyName: "The Toronto-Dominion Bank",
    marketCap: "108.50B",
    priceChange: "-1.42%",
    price: 59.82,
  },
  {
    symbol: "LMT",
    revenue: "64.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lmt.png",
    companyName: "Lockheed Martin Corporation",
    marketCap: "107.11B",
    priceChange: "1.09%",
    price: 403.96,
  },
  {
    symbol: "HSBC",
    revenue: "63.94B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HSBC.png",
    companyName: "HSBC Holdings PLC",
    marketCap: "106.85B",
    priceChange: "-0.91%",
    price: 26.15,
  },
  {
    symbol: "IBM",
    revenue: "50.61B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/IBM.png",
    companyName: "International Business Machines Corporation",
    marketCap: "106.50B",
    priceChange: "-2.79%",
    price: 118.82,
  },
  {
    symbol: "T",
    revenue: "148.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/t.png",
    companyName: "AT&T, Inc.",
    marketCap: "106.46B",
    priceChange: "-2.48%",
    price: 14.94,
  },
  {
    symbol: "INTC",
    revenue: "73.39B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/INTC.png",
    companyName: "Intel Corporation",
    marketCap: "105.61B",
    priceChange: "-5.37%",
    price: 25.72,
  },
  {
    symbol: "PYPL",
    revenue: "26.39B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pypl.png",
    companyName: "PayPal Holdings, Inc.",
    marketCap: "104.28B",
    priceChange: "-4.50%",
    price: 90.17,
  },
  {
    symbol: "AXP",
    revenue: "47.96B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/axp.png",
    companyName: "American Express Company",
    marketCap: "104.21B",
    priceChange: "-2.37%",
    price: 139,
  },
  {
    symbol: "BX",
    revenue: "17.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BX.png",
    companyName: "Blackstone Inc.",
    marketCap: "104.00B",
    priceChange: "-5.71%",
    price: 86.38,
  },
  {
    symbol: "GS",
    revenue: "51.04B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/gs.png",
    companyName: "The Goldman Sachs Group, Inc.",
    marketCap: "102.78B",
    priceChange: "-1.18%",
    price: 301.08,
  },
  {
    symbol: "SPGI",
    revenue: "9.56B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SPGI.png",
    companyName: "S&P Global Inc.",
    marketCap: "101.56B",
    priceChange: "-3.68%",
    price: 304.53,
  },
  {
    symbol: "NFLX",
    revenue: "31.03B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/nflx.png",
    companyName: "Netflix, Inc.",
    marketCap: "99.95B",
    priceChange: "-6.36%",
    price: 224.75,
  },
  {
    symbol: "SBUX",
    revenue: "31.98B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SBUX.png",
    companyName: "Starbucks Corporation",
    marketCap: "99.86B",
    priceChange: "-2.60%",
    price: 87.03,
  },
  {
    symbol: "SAP",
    revenue: "-",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SAP.png",
    companyName: "SAP SE",
    marketCap: "99.29B",
    priceChange: "-2.12%",
    price: 84.53,
  },
  {
    symbol: "SNY",
    revenue: "44.25B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SNY.png",
    companyName: "Sanofi",
    marketCap: "98.59B",
    priceChange: "-0.10%",
    price: 38.86,
  },
  {
    symbol: "BP",
    revenue: "210.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BP.png",
    companyName: "BP plc",
    marketCap: "96.98B",
    priceChange: "-0.19%",
    price: 31.08,
  },
  {
    symbol: "HDB",
    revenue: "11.71B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/hdb.png",
    companyName: "HDFC Bank Limited",
    marketCap: "96.76B",
    priceChange: "-3.27%",
    price: 57.45,
  },
  {
    symbol: "DEO",
    revenue: "18.84B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DEO.png",
    companyName: "Diageo PLC",
    marketCap: "96.42B",
    priceChange: "-0.77%",
    price: 167.3,
  },
  {
    symbol: "AMD",
    revenue: "21.58B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/AMD.png",
    companyName: "Advanced Micro Devices, Inc.",
    marketCap: "94.34B",
    priceChange: "-13.87%",
    price: 58.44,
  },
  {
    symbol: "ADP",
    revenue: "16.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/adp.png",
    companyName: "Automatic Data Processing, Inc.",
    marketCap: "94.32B",
    priceChange: "-3.31%",
    price: 227.12,
  },
  {
    symbol: "RIO",
    revenue: "63.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RIO.png",
    companyName: "Rio Tinto PLC",
    marketCap: "93.10B",
    priceChange: "0.23%",
    price: 57.3,
  },
  {
    symbol: "PLD",
    revenue: "4.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pld.png",
    companyName: "Prologis, Inc.",
    marketCap: "92.66B",
    priceChange: "-1.53%",
    price: 100.36,
  },
  {
    symbol: "BUD",
    revenue: "56.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bud.png",
    companyName: "Anheuser-Busch InBev SA/NV",
    marketCap: "92.04B",
    priceChange: "-1.09%",
    price: 45.32,
  },
  {
    symbol: "AMT",
    revenue: "10.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/amt.png",
    companyName: "American Tower Corporation",
    marketCap: "90.62B",
    priceChange: "-3.46%",
    price: 194.63,
  },
  {
    symbol: "BTI",
    revenue: "32.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BTI.png",
    companyName: "British American Tobacco PLC",
    marketCap: "83.24B",
    priceChange: "0.71%",
    price: 36.81,
  },
  {
    symbol: "BLK",
    revenue: "19.38B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/blk.png",
    companyName: "BlackRock, Inc.",
    marketCap: "82.98B",
    priceChange: "-3.71%",
    price: 550.4,
  },
  {
    symbol: "C",
    revenue: "73.91B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/c.png",
    companyName: "Citigroup, Inc.",
    marketCap: "81.71B",
    priceChange: "-2.02%",
    price: 42.19,
  },
  {
    symbol: "NOW",
    revenue: "6.60B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/now.png",
    companyName: "ServiceNow, Inc.",
    marketCap: "81.04B",
    priceChange: "-4.12%",
    price: 401.21,
  },
  {
    symbol: "SYK",
    revenue: "17.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/syk.png",
    companyName: "Stryker Corporation",
    marketCap: "78.89B",
    priceChange: "-1.37%",
    price: 208.52,
  },
  {
    symbol: "REGN",
    revenue: "14.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/regn.png",
    companyName: "Regeneron Pharmaceuticals, Inc.",
    marketCap: "78.74B",
    priceChange: "-1.30%",
    price: 722.37,
  },
  {
    symbol: "EL",
    revenue: "17.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/EL.png",
    companyName: "The Estee Lauder Companies, Inc.",
    marketCap: "78.48B",
    priceChange: "-4.07%",
    price: 219.77,
  },
  {
    symbol: "CB",
    revenue: "40.94B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cb.png",
    companyName: "Chubb Ltd.",
    marketCap: "77.23B",
    priceChange: "-2.19%",
    price: 184.68,
  },
  {
    symbol: "MO",
    revenue: "25.48B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mo.png",
    companyName: "Altria Group, Inc.",
    marketCap: "77.11B",
    priceChange: "-0.40%",
    price: 42.82,
  },
  {
    symbol: "BA",
    revenue: "60.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ba.png",
    companyName: "The Boeing Company",
    marketCap: "77.07B",
    priceChange: "-1.82%",
    price: 129.79,
  },
  {
    symbol: "NOC",
    revenue: "34.96B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NOC.png",
    companyName: "Northrop Grumman Corporation",
    marketCap: "76.75B",
    priceChange: "2.24%",
    price: 496.09,
  },
  {
    symbol: "MMC",
    revenue: "20.65B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mmc.png",
    companyName: "Marsh & McLennan Companies, Inc.",
    marketCap: "75.95B",
    priceChange: "-3.26%",
    price: 152.19,
  },
  {
    symbol: "ENB",
    revenue: "40.54B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ENB.png",
    companyName: "Enbridge Inc.",
    marketCap: "75.85B",
    priceChange: "-0.38%",
    price: 37.05,
  },
  {
    symbol: "MDLZ",
    revenue: "29.88B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mdlz.png",
    companyName: "Mondelez International, Inc.",
    marketCap: "75.74B",
    priceChange: "-1.34%",
    price: 55.26,
  },
  {
    symbol: "VRTX",
    revenue: "8.35B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VRTX.png",
    companyName: "Vertex Pharmaceuticals, Inc.",
    marketCap: "75.71B",
    priceChange: "-1.14%",
    price: 295.23,
  },
  {
    symbol: "TJX",
    revenue: "49.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/tjx.png",
    companyName: "The TJX Companies, Inc.",
    marketCap: "74.99B",
    priceChange: "-0.77%",
    price: 64.59,
  },
  {
    symbol: "CNI",
    revenue: "11.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cni.png",
    companyName: "Canadian National Railway Company",
    marketCap: "74.87B",
    priceChange: "-2.19%",
    price: 109.78,
  },
  {
    symbol: "EOG",
    revenue: "22.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/eog.png",
    companyName: "EOG Resources, Inc.",
    marketCap: "74.69B",
    priceChange: "-0.06%",
    price: 127.45,
  },
  {
    symbol: "ADI",
    revenue: "11.11B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/adi.png",
    companyName: "Analog Devices, Inc.",
    marketCap: "74.54B",
    priceChange: "-4.01%",
    price: 144.92,
  },
  {
    symbol: "INFY",
    revenue: "16.31B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/INFY.png",
    companyName: "Infosys Limited",
    marketCap: "73.90B",
    priceChange: "-2.40%",
    price: 17.06,
  },
  {
    symbol: "SNP",
    revenue: "-",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SNP.png",
    companyName: "China Petroleum & Chemical Corporation",
    marketCap: "71.70B",
    priceChange: "-",
    price: 45.66,
  },
  {
    symbol: "PGR",
    revenue: "47.71B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pgr.png",
    companyName: "The Progressive Corporation",
    marketCap: "71.36B",
    priceChange: "0.03%",
    price: 121.96,
  },
  {
    symbol: "AMAT",
    revenue: "25.16B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/amat.png",
    companyName: "Applied Materials, Inc.",
    marketCap: "71.06B",
    priceChange: "-6.26%",
    price: 82.6,
  },
  {
    symbol: "GE",
    revenue: "74.49B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ge.png",
    companyName: "General Electric Company",
    marketCap: "70.79B",
    priceChange: "-2.51%",
    price: 64.56,
  },
  {
    symbol: "TGT",
    revenue: "107.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TGT.png",
    companyName: "Target Corporation",
    marketCap: "70.12B",
    priceChange: "-2.19%",
    price: 152.34,
  },
  {
    symbol: "SO",
    revenue: "25.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SO.png",
    companyName: "The Southern Company",
    marketCap: "69.78B",
    priceChange: "-2.45%",
    price: 64.12,
  },
  {
    symbol: "ABNB",
    revenue: "7.38B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ABNB.png",
    companyName: "Airbnb, Inc.",
    marketCap: "69.41B",
    priceChange: "-2.73%",
    price: 108.54,
  },
  {
    symbol: "ZTS",
    revenue: "8.00B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/zts.png",
    companyName: "Zoetis Inc.",
    marketCap: "68.99B",
    priceChange: "-3.42%",
    price: 147.37,
  },
  {
    symbol: "VALE",
    revenue: "54.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VALE.png",
    companyName: "Vale S.A.",
    marketCap: "68.85B",
    priceChange: "-0.62%",
    price: 14.42,
  },
  {
    symbol: "DUK",
    revenue: "27.01B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DUK.png",
    companyName: "Duke Energy Corporation",
    marketCap: "68.58B",
    priceChange: "-1.87%",
    price: 89.07,
  },
  {
    symbol: "ISRG",
    revenue: "5.96B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ISRG.png",
    companyName: "Intuitive Surgical, Inc.",
    marketCap: "67.38B",
    priceChange: "-4.56%",
    price: 188.68,
  },
  {
    symbol: "BKNG",
    revenue: "14.65B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BKNG.png",
    companyName: "Booking Holdings Inc.",
    marketCap: "66.91B",
    priceChange: "-1.44%",
    price: "1,685.16",
  },
  {
    symbol: "BAM",
    revenue: "86.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bam.png",
    companyName: "Brookfield Asset Management, Inc.",
    marketCap: "66.36B",
    priceChange: "-4.01%",
    price: 40.42,
  },
  {
    symbol: "OXY",
    revenue: "34.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/OXY.png",
    companyName: "Occidental Petroleum Corporation",
    marketCap: "65.02B",
    priceChange: "-0.99%",
    price: 69.8,
  },
  {
    symbol: "CP",
    revenue: "6.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CP.png",
    companyName: "Canadian Pacific Railway Limited",
    marketCap: "63.89B",
    priceChange: "-1.43%",
    price: 68.73,
  },
  {
    symbol: "HUM",
    revenue: "89.38B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HUM.png",
    companyName: "Humana Inc.",
    marketCap: "63.71B",
    priceChange: "0.83%",
    price: 503.46,
  },
  {
    symbol: "BDX",
    revenue: "19.78B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BDX.png",
    companyName: "Becton, Dickinson and Company",
    marketCap: "63.50B",
    priceChange: "-2.51%",
    price: 222.67,
  },
  {
    symbol: "CNQ",
    revenue: "30.29B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cnq.png",
    companyName: "Canadian Natural Resources Limited",
    marketCap: "63.30B",
    priceChange: "1.59%",
    price: 54.87,
  },
  {
    symbol: "FISV",
    revenue: "17.01B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/FISV.png",
    companyName: "Fiserv, Inc.",
    marketCap: "63.13B",
    priceChange: "-0.38%",
    price: 98.7,
  },
  {
    symbol: "PNC",
    revenue: "20.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pnc.png",
    companyName: "The PNC Financial Services Group, Inc.",
    marketCap: "62.07B",
    priceChange: "-2.81%",
    price: 151.34,
  },
  {
    symbol: "GD",
    revenue: "38.44B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/gd.png",
    companyName: "General Dynamics Corporation",
    marketCap: "61.34B",
    priceChange: "0.12%",
    price: 223.68,
  },
  {
    symbol: "PXD",
    revenue: "21.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pxd.png",
    companyName: "Pioneer Natural Resources Company",
    marketCap: "61.31B",
    priceChange: "0.07%",
    price: 256.88,
  },
  {
    symbol: "GSK",
    revenue: "43.06B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GSK.png",
    companyName: "GSK plc",
    marketCap: "61.08B",
    priceChange: "0.37%",
    price: 30.11,
  },
  {
    symbol: "CME",
    revenue: "4.84B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cme.png",
    companyName: "CME Group Inc.",
    marketCap: "61.08B",
    priceChange: "-3.26%",
    price: 169.92,
  },
  {
    symbol: "SLB",
    revenue: "24.81B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SLB.png",
    companyName: "Schlumberger Limited",
    marketCap: "60.24B",
    priceChange: "0.24%",
    price: 42.59,
  },
  {
    symbol: "USB",
    revenue: "22.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/usb.png",
    companyName: "U.S. Bancorp",
    marketCap: "59.73B",
    priceChange: "-2.14%",
    price: 40.2,
  },
  {
    symbol: "MMM",
    revenue: "35.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mmm.png",
    companyName: "3M Company",
    marketCap: "59.52B",
    priceChange: "-3.24%",
    price: 107.52,
  },
  {
    symbol: "MU",
    revenue: "32.39B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mu.png",
    companyName: "Micron Technology, Inc.",
    marketCap: "58.37B",
    priceChange: "-2.93%",
    price: 52.91,
  },
  {
    symbol: "TEAM",
    revenue: "2.80B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TEAM.png",
    companyName: "Atlassian Corporation",
    marketCap: "58.19B",
    priceChange: "-4.50%",
    price: 228.24,
  },
  {
    symbol: "CCI",
    revenue: "6.75B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cci.png",
    companyName: "Crown Castle International Corp",
    marketCap: "58.18B",
    priceChange: "-2.43%",
    price: 134.35,
  },
  {
    symbol: "ITW",
    revenue: "15.19B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ITW.png",
    companyName: "Illinois Tool Works Inc.",
    marketCap: "58.03B",
    priceChange: "-2.34%",
    price: 187.41,
  },
  {
    symbol: "BMO",
    revenue: "22.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bmo.png",
    companyName: "Bank of Montreal",
    marketCap: "57.88B",
    priceChange: "-2.62%",
    price: 85.82,
  },
  {
    symbol: "TFC",
    revenue: "22.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TFC.png",
    companyName: "Truist Financial Corp.",
    marketCap: "57.74B",
    priceChange: "-3.01%",
    price: 43.53,
  },
  {
    symbol: "AON",
    revenue: "12.44B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/aon.png",
    companyName: "Aon plc",
    marketCap: "57.61B",
    priceChange: "-2.71%",
    price: 273.11,
  },
  {
    symbol: "CL",
    revenue: "17.70B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cl.png",
    companyName: "Colgate-Palmolive Company",
    marketCap: "57.55B",
    priceChange: "-0.82%",
    price: 68.99,
  },
  {
    symbol: "HCA",
    revenue: "60.11B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/hca.png",
    companyName: "HCA Healthcare, Inc.",
    marketCap: "57.54B",
    priceChange: "-0.53%",
    price: 200.46,
  },
  {
    symbol: "ATVI",
    revenue: "7.65B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/atvi.png",
    companyName: "Activision Blizzard, Inc.",
    marketCap: "57.38B",
    priceChange: "-0.65%",
    price: 73.35,
  },
  {
    symbol: "CSX",
    revenue: "13.95B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CSX.png",
    companyName: "CSX Corporation",
    marketCap: "57.32B",
    priceChange: "-2.16%",
    price: 26.77,
  },
  {
    symbol: "BSX",
    revenue: "12.33B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BSX.png",
    companyName: "Boston Scientific Corporation",
    marketCap: "56.92B",
    priceChange: "-2.19%",
    price: 39.76,
  },
  {
    symbol: "BNS",
    revenue: "24.21B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bns.png",
    companyName: "The Bank of Nova Scotia",
    marketCap: "56.22B",
    priceChange: "-0.74%",
    price: 47.18,
  },
  {
    symbol: "SNOW",
    revenue: "1.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SNOW.png",
    companyName: "Snowflake Inc.",
    marketCap: "56.03B",
    priceChange: "-7.31%",
    price: 175.1,
  },
  {
    symbol: "UBER",
    revenue: "25.55B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/UBER.png",
    companyName: "Uber Technologies, Inc.",
    marketCap: "55.58B",
    priceChange: "-5.58%",
    price: 28.07,
  },
  {
    symbol: "ETN",
    revenue: "19.78B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ETN.png",
    companyName: "Eaton Corporation PLC",
    marketCap: "54.50B",
    priceChange: "-3.95%",
    price: 136.83,
  },
  {
    symbol: "EPD",
    revenue: "51.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/epd.png",
    companyName: "Enterprise Products Partners L.P.",
    marketCap: "54.46B",
    priceChange: "0.32%",
    price: 24.99,
  },
  {
    symbol: "DG",
    revenue: "35.35B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DG.png",
    companyName: "Dollar General Corporation",
    marketCap: "54.02B",
    priceChange: "-0.90%",
    price: 239.5,
  },
  {
    symbol: "D",
    revenue: "14.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/d.png",
    companyName: "Dominion Energy, Inc.",
    marketCap: "53.60B",
    priceChange: "-2.38%",
    price: 64.39,
  },
  {
    symbol: "SHW",
    revenue: "20.78B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SHW.png",
    companyName: "The Sherwin-Williams Company",
    marketCap: "53.29B",
    priceChange: "-5.15%",
    price: 205.6,
  },
  {
    symbol: "UBS",
    revenue: "39.06B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/UBS.png",
    companyName: "UBS Group AG",
    marketCap: "52.25B",
    priceChange: "-0.68%",
    price: 14.66,
  },
  {
    symbol: "EW",
    revenue: "5.36B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/EW.png",
    companyName: "Edwards Lifesciences Corporation",
    marketCap: "52.22B",
    priceChange: "-2.60%",
    price: 84.23,
  },
  {
    symbol: "KDP",
    revenue: "13.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KDP.png",
    companyName: "Keurig Dr Pepper Inc.",
    marketCap: "51.69B",
    priceChange: "-1.72%",
    price: 36.5,
  },
  {
    symbol: "APD",
    revenue: "11.97B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/apd.png",
    companyName: "Air Products & Chemicals, Inc.",
    marketCap: "51.40B",
    priceChange: "-2.87%",
    price: 231.75,
  },
  {
    symbol: "LRCX",
    revenue: "17.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lrcx.png",
    companyName: "Lam Research Corporation",
    marketCap: "51.29B",
    priceChange: "-5.72%",
    price: 374.84,
  },
  {
    symbol: "PANW",
    revenue: "5.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/panw.png",
    companyName: "Palo Alto Networks, Inc.",
    marketCap: "50.84B",
    priceChange: "-2.77%",
    price: 169.91,
  },
  {
    symbol: "NSC",
    revenue: "11.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NSC.png",
    companyName: "Norfolk Southern Corporation",
    marketCap: "50.40B",
    priceChange: "-1.99%",
    price: 214.57,
  },
  {
    symbol: "KKR",
    revenue: "9.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KKR.png",
    companyName: "KKR & Co. Inc.",
    marketCap: "50.33B",
    priceChange: "-4.55%",
    price: 44.9,
  },
  {
    symbol: "ICE",
    revenue: "9.48B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ICE.png",
    companyName: "Intercontinental Exchange Inc.",
    marketCap: "50.27B",
    priceChange: "-3.57%",
    price: 90.02,
  },
  {
    symbol: "CHTR",
    revenue: "53.16B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CHTR.png",
    companyName: "Charter Communications, Inc.",
    marketCap: "50.21B",
    priceChange: "-3.53%",
    price: 312.53,
  },
  {
    symbol: "PSA",
    revenue: "3.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PSA.png",
    companyName: "Public Storage",
    marketCap: "49.93B",
    priceChange: "-1.49%",
    price: 283.67,
  },
  {
    symbol: "MCK",
    revenue: "268.45B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mck.png",
    companyName: "McKesson Corporation",
    marketCap: "49.83B",
    priceChange: "-1.20%",
    price: 346.68,
  },
  {
    symbol: "EQIX",
    revenue: "6.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/eqix.png",
    companyName: "Equinix, Inc.",
    marketCap: "49.35B",
    priceChange: "-2.79%",
    price: 541.86,
  },
  {
    symbol: "RELX",
    revenue: "9.54B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RELX.png",
    companyName: "Relx PLC",
    marketCap: "49.32B",
    priceChange: "-1.35%",
    price: 24.92,
  },
  {
    symbol: "TRI",
    revenue: "6.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TRI.png",
    companyName: "Thomson Reuters Corporation",
    marketCap: "49.17B",
    priceChange: "-2.52%",
    price: 102.04,
  },
  {
    symbol: "F",
    revenue: "148.03B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/f.png",
    companyName: "Ford Motor Company",
    marketCap: "49.05B",
    priceChange: "-1.29%",
    price: 12.2,
  },
  {
    symbol: "GM",
    revenue: "132.10B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GM.png",
    companyName: "General Motors Company",
    marketCap: "49.02B",
    priceChange: "-2.92%",
    price: 33.62,
  },
  {
    symbol: "ABEV",
    revenue: "13.08B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/abev.png",
    companyName: "Ambev S.A.",
    marketCap: "48.91B",
    priceChange: "-5.25%",
    price: 2.89,
  },
  {
    symbol: "ABB",
    revenue: "28.95B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ABB.png",
    companyName: "ABB Ltd",
    marketCap: "48.34B",
    priceChange: "-2.38%",
    price: 25.01,
  },
  {
    symbol: "ADM",
    revenue: "94.36B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/adm.png",
    companyName: "Archer-Daniels-Midland Company",
    marketCap: "47.89B",
    priceChange: "-0.36%",
    price: 85.44,
  },
  {
    symbol: "MNST",
    revenue: "6.01B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mnst.png",
    companyName: "Monster Beverage Corporation",
    marketCap: "47.57B",
    priceChange: "-1.58%",
    price: 90.29,
  },
  {
    symbol: "VMW",
    revenue: "13.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VMW.png",
    companyName: "VMware, Inc.",
    marketCap: "47.40B",
    priceChange: "-2.00%",
    price: 109.81,
  },
  {
    symbol: "DVN",
    revenue: "17.18B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dvn.png",
    companyName: "Devon Energy Corporation",
    marketCap: "47.17B",
    priceChange: "-0.28%",
    price: 72.04,
  },
  {
    symbol: "SNPS",
    revenue: "4.95B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SNPS.png",
    companyName: "Synopsys, Inc.",
    marketCap: "46.95B",
    priceChange: "-4.64%",
    price: 307.01,
  },
  {
    symbol: "FIS",
    revenue: "14.39B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/fis.png",
    companyName: "Fidelity National Information Services, Inc.",
    marketCap: "46.88B",
    priceChange: "-0.71%",
    price: 77.1,
  },
  {
    symbol: "MRNA",
    revenue: "23.00B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MRNA.png",
    companyName: "Moderna, Inc.",
    marketCap: "46.68B",
    priceChange: "-4.66%",
    price: 119.32,
  },
  {
    symbol: "SRE",
    revenue: "14.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/sre.png",
    companyName: "Sempra Energy",
    marketCap: "46.21B",
    priceChange: "-1.26%",
    price: 147.03,
  },
  {
    symbol: "EMR",
    revenue: "19.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/EMR.png",
    companyName: "Emerson Electric Company",
    marketCap: "46.02B",
    priceChange: "-2.06%",
    price: 77.83,
  },
  {
    symbol: "MAR",
    revenue: "17.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MAR.png",
    companyName: "Marriott International, Inc.",
    marketCap: "45.92B",
    priceChange: "-1.78%",
    price: 141.5,
  },
  {
    symbol: "NTR",
    revenue: "35.45B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NTR.png",
    companyName: "Nutrien Ltd.",
    marketCap: "45.13B",
    priceChange: "-2.04%",
    price: 83.74,
  },
  {
    symbol: "MCO",
    revenue: "5.97B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MCO.png",
    companyName: "Moody's Corporation",
    marketCap: "45.04B",
    priceChange: "-3.39%",
    price: 245.46,
  },
  {
    symbol: "ORLY",
    revenue: "13.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ORLY.png",
    companyName: "O'Reilly Automotive, Inc.",
    marketCap: "45.00B",
    priceChange: "-2.96%",
    price: 710.77,
  },
  {
    symbol: "VLO",
    revenue: "155.61B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/vlo.png",
    companyName: "Valero Energy Corporation",
    marketCap: "44.83B",
    priceChange: "-4.56%",
    price: 113.78,
  },
  {
    symbol: "SU",
    revenue: "30.55B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SU.png",
    companyName: "Suncor Energy Inc.",
    marketCap: "44.72B",
    priceChange: "-0.06%",
    price: 32.8,
  },
  {
    symbol: "GIS",
    revenue: "19.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GIS.png",
    companyName: "General Mills, Inc.",
    marketCap: "44.72B",
    priceChange: "0.51%",
    price: 75.35,
  },
  {
    symbol: "KLAC",
    revenue: "9.21B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KLAC.png",
    companyName: "KLA Corporation",
    marketCap: "44.55B",
    priceChange: "-4.07%",
    price: 314.16,
  },
  {
    symbol: "PSX",
    revenue: "151.07B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PSX.png",
    companyName: "Phillips 66",
    marketCap: "44.50B",
    priceChange: "-0.92%",
    price: 92.5,
  },
  {
    symbol: "MELI",
    revenue: "8.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MELI.png",
    companyName: "MercadoLibre, Inc.",
    marketCap: "44.40B",
    priceChange: "-5.08%",
    price: 881.99,
  },
  {
    symbol: "CTVA",
    revenue: "16.70B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CTVA.png",
    companyName: "Corteva, Inc.",
    marketCap: "43.71B",
    priceChange: "-0.10%",
    price: 60.83,
  },
  {
    symbol: "CDNS",
    revenue: "3.28B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cdns.png",
    companyName: "Cadence Design Systems, Inc.",
    marketCap: "43.52B",
    priceChange: "-5.65%",
    price: 158.9,
  },
  {
    symbol: "LNG",
    revenue: "25.25B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lng.png",
    companyName: "Cheniere Energy, Inc.",
    marketCap: "43.46B",
    priceChange: "0.86%",
    price: 174,
  },
  {
    symbol: "LHX",
    revenue: "16.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LHX.png",
    companyName: "L3Harris Technologies, Inc.",
    marketCap: "42.92B",
    priceChange: "1.73%",
    price: 224.32,
  },
  {
    symbol: "CNC",
    revenue: "138.10B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CNC.png",
    companyName: "Centene Corporation",
    marketCap: "42.77B",
    priceChange: "-6.76%",
    price: 74.82,
  },
  {
    symbol: "AEP",
    revenue: "17.92B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/aep.png",
    companyName: "American Electric Power Company, Inc.",
    marketCap: "42.63B",
    priceChange: "-1.80%",
    price: 82.99,
  },
  {
    symbol: "BIDU",
    revenue: "18.37B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BIDU.png",
    companyName: "Baidu, Inc.",
    marketCap: "42.08B",
    priceChange: "-1.82%",
    price: 120.44,
  },
  {
    symbol: "ADSK",
    revenue: "4.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/adsk.png",
    companyName: "Autodesk, Inc.",
    marketCap: "42.04B",
    priceChange: "-5.41%",
    price: 194.74,
  },
  {
    symbol: "APH",
    revenue: "11.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/aph.png",
    companyName: "Amphenol Corporation",
    marketCap: "41.74B",
    priceChange: "-3.08%",
    price: 70.17,
  },
  {
    symbol: "TRP",
    revenue: "10.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TRP.png",
    companyName: "TC Energy Corporation",
    marketCap: "41.67B",
    priceChange: "1.23%",
    price: 41.2,
  },
  {
    symbol: "AZO",
    revenue: "15.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/AZO.png",
    companyName: "AutoZone, Inc.",
    marketCap: "41.58B",
    priceChange: "-1.89%",
    price: "2,174.00",
  },
  {
    symbol: "SAN",
    revenue: "50.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SAN.png",
    companyName: "Banco Santander, S.A.",
    marketCap: "41.53B",
    priceChange: "-1.21%",
    price: 2.45,
  },
  {
    symbol: "FCX",
    revenue: "24.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/fcx.png",
    companyName: "Freeport-McMoRan, Inc.",
    marketCap: "41.38B",
    priceChange: "-2.92%",
    price: 28.95,
  },
  {
    symbol: "CMG",
    revenue: "8.15B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CMG.png",
    companyName: "Chipotle Mexican Grill, Inc.",
    marketCap: "41.06B",
    priceChange: "-1.87%",
    price: "1,478.75",
  },
  {
    symbol: "E",
    revenue: "88.38B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/e.png",
    companyName: "Eni SpA",
    marketCap: "40.96B",
    priceChange: "-0.39%",
    price: 22.92,
  },
  {
    symbol: "ECL",
    revenue: "13.53B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ECL.png",
    companyName: "Ecolab Inc.",
    marketCap: "40.90B",
    priceChange: "-3.47%",
    price: 143.51,
  },
  {
    symbol: "RSG",
    revenue: "12.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RSG.png",
    companyName: "Republic Services, Inc.",
    marketCap: "40.83B",
    priceChange: "-3.13%",
    price: 129.23,
  },
  {
    symbol: "FTNT",
    revenue: "3.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ftnt.png",
    companyName: "Fortinet, Inc.",
    marketCap: "40.59B",
    priceChange: "-4.22%",
    price: 51.47,
  },
  {
    symbol: "KHC",
    revenue: "25.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/khc.png",
    companyName: "The Kraft Heinz Company",
    marketCap: "40.48B",
    priceChange: "-1.17%",
    price: 33.03,
  },
  {
    symbol: "CTAS",
    revenue: "8.12B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CTAS.png",
    companyName: "Cintas Corporation",
    marketCap: "40.46B",
    priceChange: "-2.97%",
    price: 398.41,
  },
  {
    symbol: "TAK",
    revenue: "26.37B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TAK.png",
    companyName: "Takeda Pharmaceutical Company Limited",
    marketCap: "40.38B",
    priceChange: "0.15%",
    price: 13.14,
  },
  {
    symbol: "FDX",
    revenue: "94.75B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/FDX.png",
    companyName: "FedEx Corporation",
    marketCap: "40.18B",
    priceChange: "-0.50%",
    price: 154.41,
  },
  {
    symbol: "CRWD",
    revenue: "1.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CRWD.png",
    companyName: "CrowdStrike Holdings, Inc.",
    marketCap: "40.11B",
    priceChange: "-3.65%",
    price: 171.88,
  },
  {
    symbol: "DXCM",
    revenue: "2.67B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DXCM.png",
    companyName: "DexCom, Inc.",
    marketCap: "39.79B",
    priceChange: "7.28%",
    price: 102.14,
  },
  {
    symbol: "HES",
    revenue: "9.43B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HES.png",
    companyName: "Hess Corporation",
    marketCap: "39.69B",
    priceChange: "-1.67%",
    price: 128.2,
  },
  {
    symbol: "PAYX",
    revenue: "4.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PAYX.png",
    companyName: "Paychex, Inc.",
    marketCap: "39.50B",
    priceChange: "-1.88%",
    price: 109.59,
  },
  {
    symbol: "SMFG",
    revenue: "25.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SMFG.png",
    companyName: "Sumitomo Mitsui Financial Group, Inc.",
    marketCap: "39.36B",
    priceChange: "-1.06%",
    price: 5.62,
  },
  {
    symbol: "BBD",
    revenue: "13.72B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BBD.png",
    companyName: "Banco Bradesco S.A.",
    marketCap: "39.27B",
    priceChange: "-2.23%",
    price: 3.95,
  },
  {
    symbol: "ROP",
    revenue: "5.81B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ROP.png",
    companyName: "Roper Technologies, Inc.",
    marketCap: "39.16B",
    priceChange: "-2.88%",
    price: 369.37,
  },
  {
    symbol: "WDAY",
    revenue: "5.67B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/wday.png",
    companyName: "Workday, Inc.",
    marketCap: "39.14B",
    priceChange: "-4.15%",
    price: 152.88,
  },
  {
    symbol: "KMI",
    revenue: "17.69B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KMI.png",
    companyName: "Kinder Morgan, Inc.",
    marketCap: "39.02B",
    priceChange: "-0.86%",
    price: 17.24,
  },
  {
    symbol: "HMC",
    revenue: "108.65B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HMC.png",
    companyName: "Honda Motor Company, Ltd.",
    marketCap: "38.74B",
    priceChange: "-0.93%",
    price: 22.31,
  },
  {
    symbol: "CM",
    revenue: "16.55B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cm.png",
    companyName: "Canadian Imperial Bank of Commerce",
    marketCap: "38.50B",
    priceChange: "-1.98%",
    price: 42.56,
  },
  {
    symbol: "NGG",
    revenue: "24.28B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NGG.png",
    companyName: "National Grid PLC",
    marketCap: "38.43B",
    priceChange: "-0.85%",
    price: 50.35,
  },
  {
    symbol: "MSI",
    revenue: "8.46B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MSI.png",
    companyName: "Motorola Solutions, Inc.",
    marketCap: "38.36B",
    priceChange: "-1.86%",
    price: 229.85,
  },
  {
    symbol: "BCE",
    revenue: "18.42B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bce.png",
    companyName: "BCE, Inc.",
    marketCap: "38.29B",
    priceChange: "-0.90%",
    price: 42,
  },
  {
    symbol: "LULU",
    revenue: "7.06B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lulu.png",
    companyName: "Lululemon Athletica, Inc.",
    marketCap: "38.02B",
    priceChange: "-3.95%",
    price: 298.22,
  },
  {
    symbol: "AIG",
    revenue: "57.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/aig.png",
    companyName: "American International Group, Inc.",
    marketCap: "37.80B",
    priceChange: "-2.07%",
    price: 49.71,
  },
  {
    symbol: "A",
    revenue: "6.66B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/a.png",
    companyName: "Agilent Technologies, Inc.",
    marketCap: "37.73B",
    priceChange: "-3.59%",
    price: 127.44,
  },
  {
    symbol: "TWTR",
    revenue: "5.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TWTR.png",
    companyName: "Twitter, Inc.",
    marketCap: "37.63B",
    priceChange: "-0.43%",
    price: 49.18,
  },
  {
    symbol: "BIIB",
    revenue: "10.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BIIB.png",
    companyName: "Biogen Inc.",
    marketCap: "37.42B",
    priceChange: "-1.67%",
    price: 257.89,
  },
  {
    symbol: "SCCO",
    revenue: "10.58B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/scco.png",
    companyName: "Southern Copper Corporation",
    marketCap: "37.04B",
    priceChange: "-0.81%",
    price: 47.91,
  },
  {
    symbol: "KMB",
    revenue: "20.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KMB.png",
    companyName: "Kimberly-Clark Corporation",
    marketCap: "37.00B",
    priceChange: "-2.32%",
    price: 109.59,
  },
  {
    symbol: "PCG",
    revenue: "21.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/pcg.png",
    companyName: "PG&E Corporation",
    marketCap: "36.81B",
    priceChange: "2.05%",
    price: 14.93,
  },
  {
    symbol: "EXC",
    revenue: "28.11B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/exc.png",
    companyName: "Exelon Corporation",
    marketCap: "36.72B",
    priceChange: "-2.12%",
    price: 36.96,
  },
  {
    symbol: "AJG",
    revenue: "8.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/AJG.png",
    companyName: "Arthur J. Gallagher & Company",
    marketCap: "36.66B",
    priceChange: "-2.67%",
    price: 174.31,
  },
  {
    symbol: "SYY",
    revenue: "68.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SYY.png",
    companyName: "Sysco Corporation",
    marketCap: "36.58B",
    priceChange: "-1.47%",
    price: 72.19,
  },
  {
    symbol: "TEL",
    revenue: "15.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TEL.png",
    companyName: "TE Connectivity Ltd.",
    marketCap: "36.51B",
    priceChange: "-3.32%",
    price: 114.16,
  },
  {
    symbol: "AFL",
    revenue: "21.35B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/AFL.png",
    companyName: "Aflac Incorporated",
    marketCap: "36.46B",
    priceChange: "-2.45%",
    price: 57.69,
  },
  {
    symbol: "WMB",
    revenue: "10.75B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WMB.png",
    companyName: "The Williams Companies, Inc.",
    marketCap: "36.30B",
    priceChange: "-1.06%",
    price: 29.79,
  },
  {
    symbol: "MRVL",
    revenue: "5.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MRVL.png",
    companyName: "Marvell Technology, Inc.",
    marketCap: "36.11B",
    priceChange: "-11.70%",
    price: 42.35,
  },
  {
    symbol: "COF",
    revenue: "30.55B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cof.png",
    companyName: "Capital One Financial Corporation",
    marketCap: "36.03B",
    priceChange: "-2.96%",
    price: 93.87,
  },
  {
    symbol: "CVE",
    revenue: "48.06B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cve.png",
    companyName: "Cenovus Energy Inc.",
    marketCap: "35.89B",
    priceChange: "-0.11%",
    price: 18.6,
  },
  {
    symbol: "O",
    revenue: "2.79B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/o.png",
    companyName: "Realty Income Corporation",
    marketCap: "35.84B",
    priceChange: "-0.84%",
    price: 58.03,
  },
  {
    symbol: "ANET",
    revenue: "3.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ANET.png",
    companyName: "Arista Networks, Inc.",
    marketCap: "35.77B",
    priceChange: "-4.50%",
    price: 116.41,
  },
  {
    symbol: "ET",
    revenue: "81.76B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ET.png",
    companyName: "Energy Transfer LP",
    marketCap: "35.62B",
    priceChange: "-0.09%",
    price: 11.54,
  },
  {
    symbol: "ALL",
    revenue: "50.05B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/all.png",
    companyName: "The Allstate Corporation",
    marketCap: "35.31B",
    priceChange: "0.08%",
    price: 130.64,
  },
  {
    symbol: "MCHP",
    revenue: "7.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MCHP.png",
    companyName: "Microchip Technology Inc.",
    marketCap: "35.26B",
    priceChange: "-4.92%",
    price: 63.82,
  },
  {
    symbol: "JCI",
    revenue: "24.97B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/JCI.png",
    companyName: "Johnson Controls International PLC",
    marketCap: "34.74B",
    priceChange: "-3.83%",
    price: 50.44,
  },
  {
    symbol: "SPG",
    revenue: "5.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/spg.png",
    companyName: "Simon Property Group, Inc.",
    marketCap: "34.67B",
    priceChange: "-2.26%",
    price: 92.54,
  },
  {
    symbol: "ENPH",
    revenue: "1.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/enph.png",
    companyName: "Enphase Energy, Inc.",
    marketCap: "34.56B",
    priceChange: "-0.89%",
    price: 255.15,
  },
  {
    symbol: "SHOP",
    revenue: "5.00B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SHOP.png",
    companyName: "Shopify, Inc.",
    marketCap: "34.51B",
    priceChange: "-9.48%",
    price: 27.21,
  },
  {
    symbol: "SE",
    revenue: "11.75B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SE.png",
    companyName: "Sea Limited",
    marketCap: "34.20B",
    priceChange: "-3.02%",
    price: 60.05,
  },
  {
    symbol: "EA",
    revenue: "7.21B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ea.png",
    companyName: "Electronic Arts, Inc.",
    marketCap: "34.01B",
    priceChange: "-1.09%",
    price: 122.31,
  },
  {
    symbol: "ING",
    revenue: "18.08B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ing.png",
    companyName: "ING Group N.V.",
    marketCap: "33.98B",
    priceChange: "-1.58%",
    price: 8.73,
  },
  {
    symbol: "SQ",
    revenue: "16.29B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SQ.png",
    companyName: "Block, Inc.",
    marketCap: "33.88B",
    priceChange: "-7.30%",
    price: 57.41,
  },
  {
    symbol: "PRU",
    revenue: "64.30B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PRU.png",
    companyName: "Prudential Financial, Inc.",
    marketCap: "33.88B",
    priceChange: "-2.01%",
    price: 91.08,
  },
  {
    symbol: "MSCI",
    revenue: "2.18B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MSCI.png",
    companyName: "MSCI Inc.",
    marketCap: "33.80B",
    priceChange: "-3.85%",
    price: 419.84,
  },
  {
    symbol: "RACE",
    revenue: "4.95B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RACE.png",
    companyName: "Ferrari N.V.",
    marketCap: "33.71B",
    priceChange: "-3.08%",
    price: 185,
  },
  {
    symbol: "IQV",
    revenue: "14.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/IQV.png",
    companyName: "IQVIA Holdings Inc.",
    marketCap: "33.63B",
    priceChange: "-3.84%",
    price: 180.34,
  },
  {
    symbol: "WCN",
    revenue: "6.68B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WCN.png",
    companyName: "Waste Connections, Inc.",
    marketCap: "33.43B",
    priceChange: "-3.53%",
    price: 129.97,
  },
  {
    symbol: "XEL",
    revenue: "14.00B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/xel.png",
    companyName: "Xcel Energy Inc.",
    marketCap: "32.74B",
    priceChange: "-3.17%",
    price: 59.86,
  },
  {
    symbol: "BNTX",
    revenue: "22.31B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BNTX.png",
    companyName: "BioNTech SE",
    marketCap: "32.69B",
    priceChange: "-2.05%",
    price: 134.71,
  },
  {
    symbol: "PH",
    revenue: "15.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PH.png",
    companyName: "Parker-Hannifin Corporation",
    marketCap: "32.65B",
    priceChange: "-2.58%",
    price: 254.19,
  },
  {
    symbol: "LYG",
    revenue: "49.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lyg.png",
    companyName: "Lloyds Banking Group PLC",
    marketCap: "32.60B",
    priceChange: "-1.05%",
    price: 1.88,
  },
  {
    symbol: "LVS",
    revenue: "3.85B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LVS.png",
    companyName: "Las Vegas Sands Corp.",
    marketCap: "32.48B",
    priceChange: "-1.32%",
    price: 42.5,
  },
  {
    symbol: "ILMN",
    revenue: "4.69B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ILMN.png",
    companyName: "Illumina, Inc.",
    marketCap: "32.43B",
    priceChange: "-3.07%",
    price: 206.18,
  },
  {
    symbol: "MTB",
    revenue: "6.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mtb.png",
    companyName: "M&T Bank Corporation",
    marketCap: "31.97B",
    priceChange: "-1.11%",
    price: 182.06,
  },
  {
    symbol: "STM",
    revenue: "14.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/STM.png",
    companyName: "STMicroelectronics N.V.",
    marketCap: "31.94B",
    priceChange: "-5.13%",
    price: 32.72,
  },
  {
    symbol: "ALB",
    revenue: "4.33B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ALB.png",
    companyName: "Albemarle Corporation",
    marketCap: "31.92B",
    priceChange: "-2.99%",
    price: 272.53,
  },
  {
    symbol: "BK",
    revenue: "16.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bk.png",
    companyName: "Bank of New York Mellon Corporation",
    marketCap: "31.90B",
    priceChange: "-2.95%",
    price: 39.48,
  },
  {
    symbol: "VOD",
    revenue: "50.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VOD.png",
    companyName: "Vodafone Group PLC",
    marketCap: "31.90B",
    priceChange: "-0.88%",
    price: 11.3,
  },
  {
    symbol: "DOW",
    revenue: "60.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dow.png",
    companyName: "Dow Inc.",
    marketCap: "31.89B",
    priceChange: "-2.44%",
    price: 44.41,
  },
  {
    symbol: "DLTR",
    revenue: "27.17B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DLTR.png",
    companyName: "Dollar Tree, Inc.",
    marketCap: "31.79B",
    priceChange: "-0.13%",
    price: 141.95,
  },
  {
    symbol: "GPN",
    revenue: "8.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GPN.png",
    companyName: "Global Payments Inc.",
    marketCap: "31.11B",
    priceChange: "-0.94%",
    price: 112.24,
  },
  {
    symbol: "YUM",
    revenue: "6.68B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/YUM.png",
    companyName: "Yum! Brands, Inc.",
    marketCap: "31.00B",
    priceChange: "-1.08%",
    price: 108.93,
  },
  {
    symbol: "KR",
    revenue: "144.15B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KR.png",
    companyName: "The Kroger Company",
    marketCap: "30.78B",
    priceChange: "-1.65%",
    price: 43,
  },
  {
    symbol: "CMI",
    revenue: "24.79B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CMI.png",
    companyName: "Cummins Inc.",
    marketCap: "30.74B",
    priceChange: "-1.24%",
    price: 218.04,
  },
  {
    symbol: "PCAR",
    revenue: "25.46B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PCAR.png",
    companyName: "PACCAR Inc",
    marketCap: "30.49B",
    priceChange: "-2.25%",
    price: 87.68,
  },
  {
    symbol: "CTSH",
    revenue: "19.25B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CTSH.png",
    companyName: "Cognizant Technology Solutions",
    marketCap: "30.29B",
    priceChange: "-2.04%",
    price: 58.49,
  },
  {
    symbol: "MFC",
    revenue: "24.47B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MFC.png",
    companyName: "Manulife Financial Corporation",
    marketCap: "30.21B",
    priceChange: "-1.85%",
    price: 15.92,
  },
  {
    symbol: "NUE",
    revenue: "42.97B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NUE.png",
    companyName: "Nucor Corporation",
    marketCap: "30.11B",
    priceChange: "-2.38%",
    price: 115.01,
  },
  {
    symbol: "IMO",
    revenue: "40.73B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/imo.png",
    companyName: "Imperial Oil Ltd.",
    marketCap: "30.08B",
    priceChange: "-1.69%",
    price: 47.2,
  },
  {
    symbol: "CSGP",
    revenue: "2.06B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CSGP.png",
    companyName: "CoStar Group, Inc.",
    marketCap: "29.87B",
    priceChange: "-2.31%",
    price: 73.47,
  },
  {
    symbol: "CARR",
    revenue: "20.34B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CARR.png",
    companyName: "Carrier Global Corporation",
    marketCap: "29.73B",
    priceChange: "-5.05%",
    price: 35.33,
  },
  {
    symbol: "VICI",
    revenue: "1.84B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VICI.png",
    companyName: "VICI Properties Inc.",
    marketCap: "29.51B",
    priceChange: "-1.03%",
    price: 30.64,
  },
  {
    symbol: "AMP",
    revenue: "13.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/amp.png",
    companyName: "Ameriprise Financial, Inc.",
    marketCap: "29.41B",
    priceChange: "-1.15%",
    price: 271.86,
  },
  {
    symbol: "PUK",
    revenue: "1.81B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PUK.png",
    companyName: "Prudential PLC",
    marketCap: "29.31B",
    priceChange: "-2.02%",
    price: 20.82,
  },
  {
    symbol: "APO",
    revenue: "5.42B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/APO.png",
    companyName: "Apollo Global Management, Inc.",
    marketCap: "29.26B",
    priceChange: "-4.39%",
    price: 48.77,
  },
  {
    symbol: "ALC",
    revenue: "8.66B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ALC.png",
    companyName: "Alcon, Inc.",
    marketCap: "29.11B",
    priceChange: "-2.89%",
    price: 58.54,
  },
  {
    symbol: "ODFL",
    revenue: "5.98B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ODFL.png",
    companyName: "Old Dominion Freight Line, Inc.",
    marketCap: "29.07B",
    priceChange: "-6.18%",
    price: 260.04,
  },
  {
    symbol: "TDG",
    revenue: "5.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/tdg.png",
    companyName: "TransDigm Group Incorporated",
    marketCap: "28.93B",
    priceChange: "-2.47%",
    price: 533.48,
  },
  {
    symbol: "ED",
    revenue: "14.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ed.png",
    companyName: "Consolidated Edison, Inc.",
    marketCap: "28.93B",
    priceChange: "-2.88%",
    price: 81.58,
  },
  {
    symbol: "BBVA",
    revenue: "23.43B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BBVA.png",
    companyName: "Banco Bilbao Vizcaya Argentaria S.A.",
    marketCap: "28.88B",
    priceChange: "-1.17%",
    price: 4.51,
  },
  {
    symbol: "KEYS",
    revenue: "5.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/KEYS.png",
    companyName: "Keysight Technologies Inc.",
    marketCap: "28.80B",
    priceChange: "-4.42%",
    price: 161.06,
  },
  {
    symbol: "ABC",
    revenue: "236.33B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/abc.png",
    companyName: "AmerisourceBergen Corporation",
    marketCap: "28.47B",
    priceChange: "-1.83%",
    price: 137.35,
  },
  {
    symbol: "TU",
    revenue: "13.80B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TU.png",
    companyName: "TELUS Corporation",
    marketCap: "28.41B",
    priceChange: "-",
    price: 20.03,
  },
  {
    symbol: "TLK",
    revenue: "10.05B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TLK.png",
    companyName: "Telkom Indonesia",
    marketCap: "28.35B",
    priceChange: "-1.60%",
    price: 28.29,
  },
  {
    symbol: "SBAC",
    revenue: "2.46B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SBAC.png",
    companyName: "SBA Communications Corporation",
    marketCap: "28.31B",
    priceChange: "-2.10%",
    price: 262.4,
  },
  {
    symbol: "ON",
    revenue: "7.62B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ON.png",
    companyName: "ON Semiconductor Corporation",
    marketCap: "28.09B",
    priceChange: "-7.72%",
    price: 64.83,
  },
  {
    symbol: "BAX",
    revenue: "14.19B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bax.png",
    companyName: "Baxter International, Inc.",
    marketCap: "28.01B",
    priceChange: "-1.12%",
    price: 55.62,
  },
  {
    symbol: "DDOG",
    revenue: "1.37B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DDOG.png",
    companyName: "Datadog, Inc.",
    marketCap: "27.87B",
    priceChange: "-5.98%",
    price: 88.06,
  },
  {
    symbol: "IDXX",
    revenue: "3.31B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/IDXX.png",
    companyName: "IDEXX Laboratories, Inc.",
    marketCap: "27.74B",
    priceChange: "-3.69%",
    price: 333.24,
  },
  {
    symbol: "PEG",
    revenue: "9.35B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/peg.png",
    companyName: "Public Service Enterprise Group, Inc.",
    marketCap: "27.60B",
    priceChange: "-2.37%",
    price: 55.32,
  },
  {
    symbol: "CEG",
    revenue: "-",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CEG.png",
    companyName: "Constellation Energy Corporation",
    marketCap: "27.58B",
    priceChange: "-2.19%",
    price: 84.39,
  },
  {
    symbol: "HAL",
    revenue: "17.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/hal.png",
    companyName: "Halliburton Company",
    marketCap: "27.58B",
    priceChange: "2.01%",
    price: 30.41,
  },
  {
    symbol: "MFG",
    revenue: "12.51B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MFG.png",
    companyName: "Mizuho Financial Group, Inc.",
    marketCap: "27.53B",
    priceChange: "-",
    price: 2.22,
  },
  {
    symbol: "OTIS",
    revenue: "14.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/OTIS.png",
    companyName: "Otis Worldwide Corporation",
    marketCap: "27.42B",
    priceChange: "-2.31%",
    price: 65.26,
  },
  {
    symbol: "GOLD",
    revenue: "11.85B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/gold.png",
    companyName: "Barrick Gold Corporation",
    marketCap: "27.36B",
    priceChange: "-4.15%",
    price: 15.48,
  },
  {
    symbol: "CHT",
    revenue: "7.20B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CHT.png",
    companyName: "Chunghwa Telecom Co. Ltd.",
    marketCap: "27.16B",
    priceChange: "-0.75%",
    price: 34.23,
  },
  {
    symbol: "WELL",
    revenue: "5.42B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WELL.png",
    companyName: "Welltower Inc.",
    marketCap: "27.15B",
    priceChange: "-1.94%",
    price: 58.6,
  },
  {
    symbol: "DLR",
    revenue: "4.51B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dlr.png",
    companyName: "Digital Realty Trust, Inc.",
    marketCap: "27.15B",
    priceChange: "-2.07%",
    price: 92.45,
  },
  {
    symbol: "WIT",
    revenue: "10.51B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WIT.png",
    companyName: "Wipro Limited",
    marketCap: "27.11B",
    priceChange: "-2.68%",
    price: 4.73,
  },
  {
    symbol: "WEC",
    revenue: "8.98B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/wec.png",
    companyName: "WEC Energy Group, Inc.",
    marketCap: "26.96B",
    priceChange: "-1.20%",
    price: 85.48,
  },
  {
    symbol: "PPG",
    revenue: "17.56B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PPG.png",
    companyName: "PPG Industries, Inc.",
    marketCap: "26.88B",
    priceChange: "-2.85%",
    price: 114.37,
  },
  {
    symbol: "VRSK",
    revenue: "3.05B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VRSK.png",
    companyName: "Verisk Analytics, Inc.",
    marketCap: "26.77B",
    priceChange: "-2.92%",
    price: 170.56,
  },
  {
    symbol: "AME",
    revenue: "5.92B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/AME.png",
    companyName: "AMETEK, Inc.",
    marketCap: "26.70B",
    priceChange: "-2.86%",
    price: 116.29,
  },
  {
    symbol: "CQP",
    revenue: "13.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cqp.png",
    companyName: "Cheniere Energy Partners LP",
    marketCap: "26.67B",
    priceChange: "-1.73%",
    price: 55.11,
  },
  {
    symbol: "WBA",
    revenue: "134.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/wba.png",
    companyName: "Walgreens Boots Alliance, Inc.",
    marketCap: "26.38B",
    priceChange: "-5.36%",
    price: 30.52,
  },
  {
    symbol: "FAST",
    revenue: "6.57B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/FAST.png",
    companyName: "Fastenal Company",
    marketCap: "26.35B",
    priceChange: "-3.23%",
    price: 45.85,
  },
  {
    symbol: "DD",
    revenue: "15.14B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dd.png",
    companyName: "DuPont de Nemours, Inc.",
    marketCap: "26.23B",
    priceChange: "-1.54%",
    price: 52.36,
  },
  {
    symbol: "CPRT",
    revenue: "3.50B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CPRT.png",
    companyName: "Copart, Inc.",
    marketCap: "26.11B",
    priceChange: "-3.21%",
    price: 109.68,
  },
  {
    symbol: "BCS",
    revenue: "28.54B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BCS.png",
    companyName: "Barclays PLC",
    marketCap: "26.06B",
    priceChange: "-1.38%",
    price: 6.43,
  },
  {
    symbol: "MTD",
    revenue: "3.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MTD.png",
    companyName: "Mettler-Toledo International, Inc.",
    marketCap: "26.04B",
    priceChange: "-3.85%",
    price: "1,156.89",
  },
  {
    symbol: "ROK",
    revenue: "7.44B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ROK.png",
    companyName: "Rockwell Automation, Inc.",
    marketCap: "26.02B",
    priceChange: "-3.31%",
    price: 225.41,
  },
  {
    symbol: "HPQ",
    revenue: "64.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HPQ.png",
    companyName: "HP Inc.",
    marketCap: "25.89B",
    priceChange: "-5.44%",
    price: 25.04,
  },
  {
    symbol: "GLW",
    revenue: "14.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GLW.png",
    companyName: "Corning Incorporated",
    marketCap: "25.75B",
    priceChange: "-3.27%",
    price: 30.46,
  },
  {
    symbol: "ES",
    revenue: "10.96B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/es.png",
    companyName: "Eversource Energy",
    marketCap: "25.72B",
    priceChange: "-1.64%",
    price: 74.25,
  },
  {
    symbol: "LYB",
    revenue: "53.53B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lyb.png",
    companyName: "LyondellBasell Industries NV",
    marketCap: "25.65B",
    priceChange: "-1.87%",
    price: 78.62,
  },
  {
    symbol: "DFS",
    revenue: "10.69B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dfs.png",
    companyName: "Discover Financial Services",
    marketCap: "25.51B",
    priceChange: "-2.01%",
    price: 93.4,
  },
  {
    symbol: "GWW",
    revenue: "14.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GWW.png",
    companyName: "W.W. Grainger, Inc.",
    marketCap: "25.48B",
    priceChange: "-1.70%",
    price: 500.92,
  },
  {
    symbol: "CRH",
    revenue: "31.04B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CRH.png",
    companyName: "CRH Plc",
    marketCap: "25.44B",
    priceChange: "-3.11%",
    price: 32.38,
  },
  {
    symbol: "DELL",
    revenue: "103.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DELL.png",
    companyName: "Dell Technologies Inc.",
    marketCap: "25.36B",
    priceChange: "-7.68%",
    price: 34.6,
  },
  {
    symbol: "FANG",
    revenue: "9.11B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/fang.png",
    companyName: "Diamondback Energy, Inc.",
    marketCap: "25.32B",
    priceChange: "0.07%",
    price: 142.43,
  },
  {
    symbol: "CLR",
    revenue: "7.74B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/clr.png",
    companyName: "Continental Resources, Inc.",
    marketCap: "25.30B",
    priceChange: "-0.09%",
    price: 69.7,
  },
  {
    symbol: "NWG",
    revenue: "11.55B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NWG.png",
    companyName: "NatWest Group PLC",
    marketCap: "25.19B",
    priceChange: "-0.59%",
    price: 5.1,
  },
  {
    symbol: "FRC",
    revenue: "5.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/frc.png",
    companyName: "First Republic Bank",
    marketCap: "25.04B",
    priceChange: "-1.51%",
    price: 137.03,
  },
  {
    symbol: "DHI",
    revenue: "31.95B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DHI.png",
    companyName: "D.R. Horton, Inc.",
    marketCap: "24.99B",
    priceChange: "-2.56%",
    price: 71.91,
  },
  {
    symbol: "NOK",
    revenue: "25.23B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NOK.png",
    companyName: "Nokia Corporation",
    marketCap: "24.85B",
    priceChange: "-2.00%",
    price: 4.42,
  },
  {
    symbol: "SQM",
    revenue: "2.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SQM.png",
    companyName: "Sociedad Quimica y Minera de Chile S.A.",
    marketCap: "24.64B",
    priceChange: "-4.24%",
    price: 90.05,
  },
  {
    symbol: "EQR",
    revenue: "2.61B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/eqr.png",
    companyName: "Equity Residential",
    marketCap: "24.40B",
    priceChange: "-2.98%",
    price: 62.53,
  },
  {
    symbol: "OKE",
    revenue: "21.40B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/OKE.png",
    companyName: "ONEOK, Inc.",
    marketCap: "24.37B",
    priceChange: "-1.98%",
    price: 54.53,
  },
  {
    symbol: "ZS",
    revenue: "1.09B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ZS.png",
    companyName: "Zscaler, Inc.",
    marketCap: "24.33B",
    priceChange: "-7.01%",
    price: 170.09,
  },
  {
    symbol: "HRL",
    revenue: "12.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HRL.png",
    companyName: "Hormel Foods Corporation",
    marketCap: "24.33B",
    priceChange: "-0.82%",
    price: 44.54,
  },
  {
    symbol: "GMAB",
    revenue: "1.43B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GMAB.png",
    companyName: "Genmab A/S",
    marketCap: "24.29B",
    priceChange: "-4.41%",
    price: 35.1,
  },
  {
    symbol: "SGEN",
    revenue: "1.78B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SGEN.png",
    companyName: "Seagen, Inc.",
    marketCap: "24.21B",
    priceChange: "-3.68%",
    price: 131.26,
  },
  {
    symbol: "AVB",
    revenue: "2.44B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/avb.png",
    companyName: "AvalonBay Communities, Inc.",
    marketCap: "24.09B",
    priceChange: "-3.01%",
    price: 172.28,
  },
  {
    symbol: "ORAN",
    revenue: "48.32B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ORAN.png",
    companyName: "Orange S.A.",
    marketCap: "24.03B",
    priceChange: "0.45%",
    price: 8.9,
  },
  {
    symbol: "TROW",
    revenue: "7.29B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TROW.png",
    companyName: "T. Rowe price Group, Inc.",
    marketCap: "23.97B",
    priceChange: "-4.26%",
    price: 106.2,
  },
  {
    symbol: "SLF",
    revenue: "18.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SLF.png",
    companyName: "Sun Life Financial Inc.",
    marketCap: "23.92B",
    priceChange: "-1.27%",
    price: 40.37,
  },
  {
    symbol: "NIO",
    revenue: "5.96B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NIO.png",
    companyName: "NIO Inc.",
    marketCap: "23.83B",
    priceChange: "-6.84%",
    price: 13.76,
  },
  {
    symbol: "K",
    revenue: "14.58B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/k.png",
    companyName: "Kellogg Company",
    marketCap: "23.69B",
    priceChange: "-0.56%",
    price: 69.65,
  },
  {
    symbol: "ALNY",
    revenue: "884.25M",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ALNY.png",
    companyName: "Alnylam Pharmaceuticals, Inc.",
    marketCap: "23.50B",
    priceChange: "-3.24%",
    price: 195.81,
  },
  {
    symbol: "QSR",
    revenue: "6.13B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/QSR.png",
    companyName: "Restaurant Brands International Inc.",
    marketCap: "23.49B",
    priceChange: "-2.37%",
    price: 52.31,
  },
  {
    symbol: "BKR",
    revenue: "20.46B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BKR.png",
    companyName: "Baker Hughes Company",
    marketCap: "23.31B",
    priceChange: "-3.62%",
    price: 22.88,
  },
  {
    symbol: "CAJ",
    revenue: "26.92B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CAJ.png",
    companyName: "Canon, Inc.",
    marketCap: "23.26B",
    priceChange: "-1.09%",
    price: 22.65,
  },
  {
    symbol: "IT",
    revenue: "5.10B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/IT.png",
    companyName: "Gartner, Inc.",
    marketCap: "23.25B",
    priceChange: "-2.24%",
    price: 294.01,
  },
  {
    symbol: "CTRA",
    revenue: "6.92B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CTRA.png",
    companyName: "Coterra Energy Inc.",
    marketCap: "23.23B",
    priceChange: "1.18%",
    price: 29.2,
  },
  {
    symbol: "EXR",
    revenue: "1.76B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/exr.png",
    companyName: "Extra Space Storage, Inc.",
    marketCap: "23.21B",
    priceChange: "-4.03%",
    price: 165.17,
  },
  {
    symbol: "AWK",
    revenue: "3.82B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/awk.png",
    companyName: "American Water Works Company, Inc.",
    marketCap: "23.17B",
    priceChange: "-2.89%",
    price: 127.45,
  },
  {
    symbol: "RJF",
    revenue: "10.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RJF.png",
    companyName: "Raymond James Financial, Inc.",
    marketCap: "23.12B",
    priceChange: "-1.02%",
    price: 107.12,
  },
  {
    symbol: "APTV",
    revenue: "16.02B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/APTV.png",
    companyName: "Aptiv PLC",
    marketCap: "23.08B",
    priceChange: "-3.60%",
    price: 85.19,
  },
  {
    symbol: "FNV",
    revenue: "1.34B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/fnv.png",
    companyName: "Franco-Nevada Corporation",
    marketCap: "23.01B",
    priceChange: "-4.17%",
    price: 120.16,
  },
  {
    symbol: "TSN",
    revenue: "52.36B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TSN.png",
    companyName: "Tyson Foods, Inc.",
    marketCap: "22.98B",
    priceChange: "-2.49%",
    price: 63.89,
  },
  {
    symbol: "BSBR",
    revenue: "6.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/BSBR.png",
    companyName: "Banco Santander Brasil S.A.",
    marketCap: "22.96B",
    priceChange: "-1.14%",
    price: 6.09,
  },
  {
    symbol: "SIRI",
    revenue: "8.92B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/SIRI.png",
    companyName: "Sirius XM Holdings Inc.",
    marketCap: "22.86B",
    priceChange: "-1.01%",
    price: 5.87,
  },
  {
    symbol: "STT",
    revenue: "12.08B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/STT.png",
    companyName: "State Street Corporation",
    marketCap: "22.83B",
    priceChange: "-2.89%",
    price: 62.11,
  },
  {
    symbol: "ZM",
    revenue: "4.30B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ZM.png",
    companyName: "Zoom Video Communications, Inc.",
    marketCap: "22.80B",
    priceChange: "-2.25%",
    price: 76.59,
  },
  {
    symbol: "ZBH",
    revenue: "7.41B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ZBH.png",
    companyName: "Zimmer Biomet Holdings, Inc.",
    marketCap: "22.72B",
    priceChange: "-2.12%",
    price: 108.26,
  },
  {
    symbol: "FITB",
    revenue: "7.77B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/fitb.png",
    companyName: "Fifth Third Bancorp",
    marketCap: "22.71B",
    priceChange: "-1.28%",
    price: 33.1,
  },
  {
    symbol: "IFF",
    revenue: "12.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/iff.png",
    companyName: "International Flavors & Fragrances, Inc.",
    marketCap: "22.56B",
    priceChange: "-2.10%",
    price: 88.5,
  },
  {
    symbol: "WTW",
    revenue: "8.87B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WTW.png",
    companyName: "Willis Towers Watson PLC",
    marketCap: "22.54B",
    priceChange: "-2.70%",
    price: 204.93,
  },
  {
    symbol: "EIX",
    revenue: "16.61B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/eix.png",
    companyName: "Edison International",
    marketCap: "22.36B",
    priceChange: "-0.03%",
    price: 58.63,
  },
  {
    symbol: "CBRE",
    revenue: "30.45B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CBRE.png",
    companyName: "CBRE Group, Inc.",
    marketCap: "22.30B",
    priceChange: "-3.13%",
    price: 69.43,
  },
  {
    symbol: "LEN",
    revenue: "31.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LEN.png",
    companyName: "Lennar Corporation",
    marketCap: "22.17B",
    priceChange: "-2.56%",
    price: 78.11,
  },
  {
    symbol: "LCID",
    revenue: "181.64M",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/lcid.png",
    companyName: "Lucid Group, Inc.",
    marketCap: "22.10B",
    priceChange: "-8.61%",
    price: 13.17,
  },
  {
    symbol: "BR",
    revenue: "5.71B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/br.png",
    companyName: "Broadridge Financial Solutions, Inc.",
    marketCap: "22.07B",
    priceChange: "-1.77%",
    price: 142.87,
  },
  {
    symbol: "ARE",
    revenue: "2.38B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ARE.png",
    companyName: "Alexandria Real Estate Equities, Inc.",
    marketCap: "21.99B",
    priceChange: "-3.29%",
    price: 134.74,
  },
  {
    symbol: "GPC",
    revenue: "20.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/GPC.png",
    companyName: "Genuine Parts Company",
    marketCap: "21.76B",
    priceChange: "-1.89%",
    price: 153.87,
  },
  {
    symbol: "TSCO",
    revenue: "13.26B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TSCO.png",
    companyName: "Tractor Supply Company",
    marketCap: "21.60B",
    priceChange: "-2.73%",
    price: 194.62,
  },
  {
    symbol: "CDW",
    revenue: "22.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CDW.png",
    companyName: "CDW Corporation",
    marketCap: "21.59B",
    priceChange: "-3.26%",
    price: 159.62,
  },
  {
    symbol: "FTV",
    revenue: "5.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/FTV.png",
    companyName: "Fortive Corporation",
    marketCap: "21.36B",
    priceChange: "-2.25%",
    price: 60.06,
  },
  {
    symbol: "WY",
    revenue: "10.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/WY.png",
    companyName: "Weyerhaeuser Company",
    marketCap: "21.22B",
    priceChange: "-1.75%",
    price: 28.66,
  },
  {
    symbol: "ERIC",
    revenue: "25.81B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ERIC.png",
    companyName: "Ericsson",
    marketCap: "21.20B",
    priceChange: "-1.93%",
    price: 6.1,
  },
  {
    symbol: "CCEP",
    revenue: "16.97B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CCEP.png",
    companyName: "Coca-Cola Europacific Partners PLC",
    marketCap: "20.94B",
    priceChange: "-0.82%",
    price: 44.68,
  },
  {
    symbol: "VMC",
    revenue: "6.62B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/VMC.png",
    companyName: "Vulcan Materials Company",
    marketCap: "20.93B",
    priceChange: "-2.90%",
    price: 157.49,
  },
  {
    symbol: "CF",
    revenue: "10.16B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/cf.png",
    companyName: "CF Industries Holdings, Inc.",
    marketCap: "20.88B",
    priceChange: "-0.88%",
    price: 104.8,
  },
  {
    symbol: "DTE",
    revenue: "17.86B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dte.png",
    companyName: "DTE Energy Company",
    marketCap: "20.82B",
    priceChange: "-2.91%",
    price: 107.49,
  },
  {
    symbol: "HIG",
    revenue: "22.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/HIG.png",
    companyName: "The Hartford Financial Services Group, Inc.",
    marketCap: "20.69B",
    priceChange: "-1.23%",
    price: 64.04,
  },
  {
    symbol: "EFX",
    revenue: "5.16B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/efx.png",
    companyName: "Equifax, Inc.",
    marketCap: "20.66B",
    priceChange: "-3.16%",
    price: 168.82,
  },
  {
    symbol: "EBAY",
    revenue: "10.02B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ebay.png",
    companyName: "eBay Inc.",
    marketCap: "20.63B",
    priceChange: "-3.45%",
    price: 37.55,
  },
  {
    symbol: "FE",
    revenue: "11.59B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/fe.png",
    companyName: "FirstEnergy Corp.",
    marketCap: "20.63B",
    priceChange: "-2.04%",
    price: 36.1,
  },
  {
    symbol: "ETR",
    revenue: "12.35B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ETR.png",
    companyName: "Entergy Corporation",
    marketCap: "20.59B",
    priceChange: "-1.44%",
    price: 101.23,
  },
  {
    symbol: "MOH",
    revenue: "30.27B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/moh.png",
    companyName: "Molina Healthcare Inc.",
    marketCap: "20.26B",
    priceChange: "-1.50%",
    price: 348.76,
  },
  {
    symbol: "EC",
    revenue: "22.57B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/EC.png",
    companyName: "Ecopetrol S.A.",
    marketCap: "20.21B",
    priceChange: "-0.78%",
    price: 10.2,
  },
  {
    symbol: "SIVB",
    revenue: "5.88B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/sivb.png",
    companyName: "SVB Financial Group",
    marketCap: "20.17B",
    priceChange: "-4.24%",
    price: 341.47,
  },
  {
    symbol: "TTWO",
    revenue: "3.79B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TTWO.png",
    companyName: "Take-Two Interactive Software, Inc.",
    marketCap: "20.12B",
    priceChange: "-0.54%",
    price: 120.73,
  },
  {
    symbol: "MLM",
    revenue: "5.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/MLM.png",
    companyName: "Martin Marietta Materials, Inc.",
    marketCap: "19.98B",
    priceChange: "-3.05%",
    price: 320.25,
  },
  {
    symbol: "ULTA",
    revenue: "9.37B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ULTA.png",
    companyName: "Ulta Beauty, Inc.",
    marketCap: "19.87B",
    priceChange: "-1.05%",
    price: 387.98,
  },
  {
    symbol: "INVH",
    revenue: "2.12B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/INVH.png",
    companyName: "Invitation Homes Inc.",
    marketCap: "19.83B",
    priceChange: "-4.01%",
    price: 32.35,
  },
  {
    symbol: "MKC",
    revenue: "6.39B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mkc.png",
    companyName: "McCormick & Company, Inc.",
    marketCap: "19.77B",
    priceChange: "1.92%",
    price: 73.44,
  },
  {
    symbol: "EPAM",
    revenue: "4.46B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/epam.png",
    companyName: "EPAM Systems, Inc.",
    marketCap: "19.50B",
    priceChange: "-4.58%",
    price: 340,
  },
  {
    symbol: "BEP",
    revenue: "4.47B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/bep.png",
    companyName: "Brookfield Renewable Partners L.P.",
    marketCap: "19.49B",
    priceChange: "-1.84%",
    price: 30.41,
  },
  {
    symbol: "AEM",
    revenue: "4.83B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/AEM.png",
    companyName: "Agnico Eagle Mines Limited",
    marketCap: "19.42B",
    priceChange: "-5.52%",
    price: 42.64,
  },
  {
    symbol: "LPLA",
    revenue: "8.22B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LPLA.png",
    companyName: "LPL Financial Holdings Inc.",
    marketCap: "19.34B",
    priceChange: "-1.60%",
    price: 242.48,
  },
  {
    symbol: "RCI",
    revenue: "11.68B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/RCI.png",
    companyName: "Rogers Communications Inc.",
    marketCap: "19.17B",
    priceChange: "0.16%",
    price: 37.68,
  },
  {
    symbol: "ARES",
    revenue: "3.58B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ARES.png",
    companyName: "Ares Management Corporation",
    marketCap: "19.16B",
    priceChange: "-3.02%",
    price: 65.19,
  },
  {
    symbol: "RF",
    revenue: "6.62B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/rf.png",
    companyName: "Regions Financial Corporation",
    marketCap: "19.11B",
    priceChange: "-1.73%",
    price: 20.45,
  },
  {
    symbol: "DASH",
    revenue: "5.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/DASH.png",
    companyName: "DoorDash, Inc.",
    marketCap: "19.07B",
    priceChange: "-6.79%",
    price: 49.39,
  },
  {
    symbol: "HBAN",
    revenue: "6.77B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/hban.png",
    companyName: "Huntington Bancshares Incorporated",
    marketCap: "19.05B",
    priceChange: "-2.87%",
    price: 13.21,
  },
  {
    symbol: "TEF",
    revenue: "44.63B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/TEF.png",
    companyName: "Telefonica S.A.",
    marketCap: "19.01B",
    priceChange: "-",
    price: 3.23,
  },
  {
    symbol: "ANSS",
    revenue: "2.00B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/anss.png",
    companyName: "ANSYS, Inc.",
    marketCap: "19.01B",
    priceChange: "-6.00%",
    price: 218.3,
  },
  {
    symbol: "MRO",
    revenue: "7.31B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/mro.png",
    companyName: "Marathon Oil Corporation",
    marketCap: "18.93B",
    priceChange: "-1.10%",
    price: 27.94,
  },
  {
    symbol: "LUV",
    revenue: "21.15B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/luv.png",
    companyName: "Southwest Airlines Company",
    marketCap: "18.91B",
    priceChange: "-2.06%",
    price: 31.87,
  },
  {
    symbol: "DAL",
    revenue: "41.80B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/dal.png",
    companyName: "Delta Air Lines, Inc.",
    marketCap: "18.84B",
    priceChange: "-4.02%",
    price: 29.39,
  },
  {
    symbol: "LI",
    revenue: "5.48B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LI.png",
    companyName: "Li Auto, Inc.",
    marketCap: "18.79B",
    priceChange: "-6.59%",
    price: 19.57,
  },
  {
    symbol: "ARGX",
    revenue: "31.04M",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ARGX.png",
    companyName: "Argenx SE",
    marketCap: "18.65B",
    priceChange: "-4.15%",
    price: 353.47,
  },
  {
    symbol: "LH",
    revenue: "15.72B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LH.png",
    companyName: "Laboratory Corporation of America Holdings",
    marketCap: "18.59B",
    priceChange: "-2.22%",
    price: 205.61,
  },
  {
    symbol: "WST",
    revenue: "2.93B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/wst.png",
    companyName: "West Pharmaceutical Services, Inc.",
    marketCap: "18.50B",
    priceChange: "-2.51%",
    price: 249.82,
  },
  {
    symbol: "IR",
    revenue: "5.52B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/IR.png",
    companyName: "Ingersoll Rand Inc.",
    marketCap: "18.41B",
    priceChange: "-2.89%",
    price: 45.65,
  },
  {
    symbol: "PWR",
    revenue: "15.47B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/PWR.png",
    companyName: "Quanta Services, Inc.",
    marketCap: "18.38B",
    priceChange: "-2.79%",
    price: 128.53,
  },
  {
    symbol: "PPL",
    revenue: "6.48B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ppl.png",
    companyName: "PPL Corporation",
    marketCap: "18.17B",
    priceChange: "-2.99%",
    price: 24.68,
  },
  {
    symbol: "NET",
    revenue: "812.63M",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/NET.png",
    companyName: "Cloudflare, Inc.",
    marketCap: "18.14B",
    priceChange: "-9.23%",
    price: 55.39,
  },
  {
    symbol: "LYV",
    revenue: "11.64B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/LYV.png",
    companyName: "Live Nation Entertainment, Inc.",
    marketCap: "18.08B",
    priceChange: "-1.57%",
    price: 78.61,
  },
  {
    symbol: "ZI",
    revenue: "928.70M",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ZI.png",
    companyName: "ZoomInfo Technologies, Inc.",
    marketCap: "17.91B",
    priceChange: "-8.68%",
    price: 44.4,
  },
  {
    symbol: "NTRS",
    revenue: "6.81B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ntrs.png",
    companyName: "Northern Trust Corporation",
    marketCap: "17.91B",
    priceChange: "-3.06%",
    price: 85.95,
  },
  {
    symbol: "CAH",
    revenue: "181.36B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/CAH.png",
    companyName: "Cardinal Health, Inc.",
    marketCap: "17.87B",
    priceChange: "-1.76%",
    price: 68.22,
  },
  {
    symbol: "TTM",
    revenue: "33.81B",
    logoUrl: "https://eodhistoricaldata.com/img/logos/US/ttm.png",
    companyName: "Tata Motors Ltd.",
    marketCap: "17.85B",
    priceChange: "-2.76%",
    price: 24.27,
  },
];
